version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bank-postgres
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"